import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/navbar.jsx";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "eatthefrog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider frontendApi="pk_test_cHJlc2VudC1tYXlmbHktMjYuY2xlcmsuYWNjb3VudHMuZGV2JA">

       <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      </body>
    </html>
    </ClerkProvider>
   
  );
}
